from dataclasses import dataclass, field
from datetime import datetime

from backend.utils.output_manager import OutputManager


@dataclass
class PipelineContext:
    """
    Shared runtime context for one GeoSentinel analysis.
    """

    aoi_id: str
    aoi_name: str

    timestamp: datetime = field(default_factory=datetime.now)

    pipeline_version: str = "GeoSentinel AI v2.0"

    output_manager: OutputManager = field(init=False)

    metadata: dict = field(default_factory=dict)

    outputs: dict = field(default_factory=dict)

    def __post_init__(self):

        self.output_manager = OutputManager(self.aoi_id)

    @property
    def analysis_directory(self):

        return self.output_manager.directory

    def register_output(
        self,
        key: str,
        path,
    ):
        """
        Register an output generated by any model.
        """

        self.outputs[key] = str(path)

    def get_output(
        self,
        key: str,
    ):

        return self.outputs.get(key)

    def add_metadata(
        self,
        key: str,
        value,
    ):

        self.metadata[key] = value