"""
research_outputs.py

GeoSentinel AI — Research Output Generator

Produces structured research artifacts after every pipeline run:
  - analysis.json        (complete machine-readable analysis)
  - mission_summary.json (headline metrics)
  - evidence.json        (per-model evidence breakdown)
  - trend.json           (historical trends)
  - confidence.json      (detailed confidence breakdown)
  - report.md            (Markdown intelligence report)
  - report.html          (HTML intelligence report)

All paths come from OutputManager.default_files().
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ================================================================
# HTML template (minimal, embeds no external resources)
# ================================================================

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GeoSentinel Intelligence Report — {aoi_name}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px;
          margin: 40px auto; padding: 0 24px; background: #f5f5f5; color: #1a1a1a; }}
  h1 {{ color: #0a2540; border-bottom: 3px solid #1565c0; padding-bottom: 8px; }}
  h2 {{ color: #1565c0; margin-top: 28px; }}
  .metric-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }}
  .metric {{ background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 14px;
             text-align: center; }}
  .metric .value {{ font-size: 1.8em; font-weight: bold; color: #0a2540; }}
  .metric .label {{ font-size: 0.8em; color: #666; text-transform: uppercase; }}
  .badge-high {{ background: #d32f2f; color: #fff; padding: 3px 10px; border-radius: 12px; }}
  .badge-medium {{ background: #f57c00; color: #fff; padding: 3px 10px; border-radius: 12px; }}
  .badge-low {{ background: #2e7d32; color: #fff; padding: 3px 10px; border-radius: 12px; }}
  .report-body {{ background: #fff; border: 1px solid #ddd; border-radius: 8px;
                  padding: 24px; margin-top: 16px; white-space: pre-wrap;
                  font-size: 0.95em; line-height: 1.6; }}
  .footer {{ margin-top: 40px; font-size: 0.8em; color: #999; text-align: center; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; }}
  th {{ background: #0a2540; color: #fff; padding: 8px 12px; text-align: left; }}
  td {{ border-bottom: 1px solid #eee; padding: 8px 12px; }}
</style>
</head>
<body>
<h1>🛰 GeoSentinel Intelligence Report</h1>
<p><strong>AOI:</strong> {aoi_name} ({aoi_id}) &nbsp;|&nbsp;
   <strong>Generated:</strong> {timestamp} &nbsp;|&nbsp;
   <strong>Version:</strong> {pipeline_version}</p>

<div class="metric-grid">
  <div class="metric"><div class="value">{confidence_score:.1f}%</div>
    <div class="label">Mission Confidence</div></div>
  <div class="metric"><div class="value">{change_percentage:.2f}%</div>
    <div class="label">Change Detected</div></div>
  <div class="metric"><div class="value">{model_agreement:.1f}%</div>
    <div class="label">Model Agreement</div></div>
</div>

<h2>Intelligence Report</h2>
<div class="report-body">{report_body}</div>

<h2>Evidence Summary</h2>
<table>
  <tr><th>Model</th><th>Finding</th><th>Confidence</th></tr>
  {evidence_rows}
</table>

<h2>Confidence Breakdown</h2>
<table>
  <tr><th>Component</th><th>Score</th></tr>
  {confidence_rows}
</table>

<div class="footer">
  Generated by GeoSentinel AI v1.0 | Persistent Earth Observation Intelligence Platform
</div>
</body>
</html>
"""


def _safe_json(obj: Any) -> Any:
    """Make objects JSON-serializable (handles Path, sets, etc.)."""
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, set):
        return list(obj)
    return str(obj)


def _write_json(path: Path, data: Any) -> bool:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=4, default=_safe_json)
        return True
    except Exception as exc:
        logger.warning("Could not write %s: %s", path, exc)
        return False


def generate_research_outputs(
    output_paths: dict,
    aoi_id: str,
    aoi_name: str,
    pipeline_version: str,
    execution_time: float,
    confidence_result,           # MissionConfidenceEngine result
    fusion_results: dict,
    prithvi_results: dict,
    changestar_results: dict,
    dynamic_world_results: dict,
    grounding_dino_results: dict,
    evidence_results: dict,
    reliability_results: dict,
    historical_results: dict,
    intelligence_report: str,
    semantic_results: dict,
    preprocessing_results: Optional[dict] = None,
) -> dict:
    """
    Generate all research output files.

    Returns
    -------
    dict  – {key: path_or_None}  for each generated file.
    """
    preprocessing_results = preprocessing_results or {}
    generated = {}
    now = datetime.utcnow().isoformat() + "Z"

    # ----------------------------------------------------------------
    # 1. analysis.json  (comprehensive machine-readable record)
    # ----------------------------------------------------------------
    analysis_data = {
        "schema_version": "1.0",
        "generated_at": now,
        "aoi_id": aoi_id,
        "aoi_name": aoi_name,
        "pipeline_version": pipeline_version,
        "execution_time_seconds": execution_time,
        "confidence": {
            "score": confidence_result.score,
            "level": confidence_result.level,
            "breakdown": confidence_result.breakdown,
            "reasoning": confidence_result.reasoning,
        },
        "fusion": fusion_results,
        "prithvi": prithvi_results,
        "changestar": changestar_results,
        "dynamic_world": dynamic_world_results,
        "grounding_dino": grounding_dino_results,
        "evidence": evidence_results,
        "reliability": reliability_results,
        "historical": historical_results,
        "semantic_change": semantic_results,
        "preprocessing": preprocessing_results,
    }
    p = output_paths.get("analysis_json")
    if p and _write_json(Path(p), analysis_data):
        generated["analysis_json"] = str(p)

    # ----------------------------------------------------------------
    # 2. mission_summary.json  (headline metrics — dashboard/API use)
    # ----------------------------------------------------------------
    change_pct = fusion_results.get("change_percentage", 0.0)
    structural = fusion_results.get("structural_change", 0.0)
    severity = fusion_results.get("change_severity", "Unknown")
    model_agreement = fusion_results.get("model_agreement_score", 0.0)
    evidence_score = fusion_results.get("overall_evidence_score", 0.0)
    conflicts = fusion_results.get("conflicts", [])
    cloud_pct = (
        preprocessing_results.get("cloud_fraction", {}).get("average", 0.0)
    )
    water_pct = (
        preprocessing_results.get("water_fraction", {}).get("average", 0.0)
    )

    mission_summary = {
        "aoi_id": aoi_id,
        "aoi_name": aoi_name,
        "generated_at": now,
        "confidence_score": confidence_result.score,
        "confidence_level": confidence_result.level,
        "change_percentage": change_pct,
        "structural_change": structural,
        "change_severity": severity,
        "model_agreement_score": model_agreement,
        "overall_evidence_score": evidence_score,
        "cloud_coverage": cloud_pct,
        "water_influence": water_pct,
        "conflicts": conflicts,
        "conflict_count": len(conflicts),
        "mission_summary": fusion_results.get("mission_summary", ""),
        "assessment": fusion_results.get("assessment", ""),
        "execution_time_seconds": execution_time,
    }
    p = output_paths.get("mission_summary_json")
    if p and _write_json(Path(p), mission_summary):
        generated["mission_summary_json"] = str(p)

    # ----------------------------------------------------------------
    # 3. evidence.json  (per-model evidence breakdown)
    # ----------------------------------------------------------------
    evidence_data = {
        "generated_at": now,
        "aoi_id": aoi_id,
        "validated_evidence": fusion_results.get("validated_evidence", []),
        "reasoned_evidence": fusion_results.get("reasoned_evidence", []),
        "agreement_matrix": fusion_results.get("agreement_matrix", {}),
        "contradiction_matrix": fusion_results.get("contradiction_matrix", {}),
        "evidence_score": evidence_results.get("evidence_score", 0),
        "evidence_agreement": evidence_results.get("agreement", ""),
        "reliability": {
            k: {"score": v.score if hasattr(v, "score") else v,
                "reasoning": v.reasoning if hasattr(v, "reasoning") else ""}
            for k, v in reliability_results.items()
        } if isinstance(reliability_results, dict) else {},
    }
    p = output_paths.get("evidence_json")
    if p and _write_json(Path(p), evidence_data):
        generated["evidence_json"] = str(p)

    # ----------------------------------------------------------------
    # 4. trend.json  (historical trends)
    # ----------------------------------------------------------------
    trend_data = {
        "generated_at": now,
        "aoi_id": aoi_id,
        "analyses_count": historical_results.get("analyses", 0),
        "change_trend": str(historical_results.get("change_trend", "")),
        "confidence_trend": str(
            historical_results.get("confidence_trend", "")
        ),
        "activity_score": historical_results.get("activity_score", 0),
        "anomalies": historical_results.get("anomalies", []),
        "landcover_history": historical_results.get("landcover", []),
        "temporal_evidence": historical_results.get("temporal_evidence", []),
    }
    p = output_paths.get("trend_json")
    if p and _write_json(Path(p), trend_data):
        generated["trend_json"] = str(p)

    # ----------------------------------------------------------------
    # 5. confidence.json  (detailed confidence breakdown)
    # ----------------------------------------------------------------
    confidence_data = {
        "generated_at": now,
        "aoi_id": aoi_id,
        "overall_score": confidence_result.score,
        "level": confidence_result.level,
        "reasoning": confidence_result.reasoning,
        "breakdown": confidence_result.breakdown,
        "cloud_coverage": cloud_pct,
        "water_influence": water_pct,
        "model_agreement": model_agreement,
        "evidence_score": evidence_score,
        "image_quality": (
            preprocessing_results.get("image_quality", {})
            .get("valid_fraction", 0.0)
        ),
        "spatial_consistency": (
            fusion_results.get("agreement_matrix", {})
            .get("prithvi_vs_dynamic_world", 0.0)
        ),
        "temporal_consistency": (
            fusion_results.get("agreement_matrix", {})
            .get("changestar_vs_ssim", 0.0)
        ),
    }
    p = output_paths.get("confidence_json")
    if p and _write_json(Path(p), confidence_data):
        generated["confidence_json"] = str(p)

    # ----------------------------------------------------------------
    # 6. report.md  (Markdown intelligence report)
    # ----------------------------------------------------------------
    md = _build_markdown_report(
        aoi_id=aoi_id,
        aoi_name=aoi_name,
        pipeline_version=pipeline_version,
        now=now,
        confidence_result=confidence_result,
        fusion_results=fusion_results,
        intelligence_report=intelligence_report,
        cloud_pct=cloud_pct,
        water_pct=water_pct,
        model_agreement=model_agreement,
        evidence_score=evidence_score,
        historical_results=historical_results,
        conflicts=conflicts,
    )
    p = output_paths.get("report_md")
    if p:
        try:
            Path(p).parent.mkdir(parents=True, exist_ok=True)
            Path(p).write_text(md, encoding="utf-8")
            generated["report_md"] = str(p)
        except Exception as exc:
            logger.warning("Could not write report.md: %s", exc)

    # ----------------------------------------------------------------
    # 7. report.html  (HTML intelligence report)
    # ----------------------------------------------------------------
    html = _build_html_report(
        aoi_id=aoi_id,
        aoi_name=aoi_name,
        pipeline_version=pipeline_version,
        now=now,
        confidence_result=confidence_result,
        fusion_results=fusion_results,
        intelligence_report=intelligence_report,
        cloud_pct=cloud_pct,
        model_agreement=model_agreement,
        evidence_score=evidence_score,
        validated_evidence=fusion_results.get("validated_evidence", []),
    )
    p = output_paths.get("report_html")
    if p:
        try:
            Path(p).parent.mkdir(parents=True, exist_ok=True)
            Path(p).write_text(html, encoding="utf-8")
            generated["report_html"] = str(p)
        except Exception as exc:
            logger.warning("Could not write report.html: %s", exc)

    return generated


# ----------------------------------------------------------------
# Markdown builder
# ----------------------------------------------------------------

def _build_markdown_report(
    aoi_id,
    aoi_name,
    pipeline_version,
    now,
    confidence_result,
    fusion_results,
    intelligence_report,
    cloud_pct,
    water_pct,
    model_agreement,
    evidence_score,
    historical_results,
    conflicts,
) -> str:
    lines = [
        f"# 🛰 GeoSentinel Intelligence Report",
        f"",
        f"**AOI:** {aoi_name} (`{aoi_id}`)  ",
        f"**Generated:** {now}  ",
        f"**Version:** {pipeline_version}  ",
        f"",
        f"---",
        f"",
        f"## Mission Status",
        f"",
        f"| Metric | Value |",
        f"| ------ | ----- |",
        f"| Mission Confidence | {confidence_result.score:.1f}% ({confidence_result.level}) |",
        f"| Change Detected | {fusion_results.get('change_percentage', 0):.2f}% |",
        f"| Structural Change | {fusion_results.get('structural_change', 0):.2f}% |",
        f"| Change Severity | {fusion_results.get('change_severity', 'Unknown')} |",
        f"| Model Agreement | {model_agreement:.1f}% |",
        f"| Overall Evidence Score | {evidence_score:.1f}% |",
        f"| Cloud Coverage | {cloud_pct:.1f}% |",
        f"| Water Influence | {water_pct:.1f}% |",
        f"",
        f"---",
        f"",
        f"## Intelligence Report",
        f"",
        intelligence_report or "_Report unavailable._",
        f"",
        f"---",
        f"",
    ]

    if conflicts:
        lines += [
            f"## Conflicts & Uncertainties",
            f"",
        ]
        for c in conflicts:
            lines.append(f"- {c}")
        lines.append("")

    # Historical trend
    change_trend = historical_results.get("change_trend")
    if change_trend:
        lines += [
            f"## Historical Trend",
            f"",
            f"- **Change trend:** {change_trend}",
            f"- **Analyses in history:** {historical_results.get('analyses', 0)}",
            f"- **Activity score:** {historical_results.get('activity_score', 0)}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"_Generated by GeoSentinel AI v1.0 — Persistent Earth Observation Intelligence Platform_",
    ]

    return "\n".join(lines)


# ----------------------------------------------------------------
# HTML builder
# ----------------------------------------------------------------

def _build_html_report(
    aoi_id,
    aoi_name,
    pipeline_version,
    now,
    confidence_result,
    fusion_results,
    intelligence_report,
    cloud_pct,
    model_agreement,
    evidence_score,
    validated_evidence,
) -> str:
    level = confidence_result.level.lower()
    badge_class = {
        "high": "badge-high",
        "medium": "badge-medium",
        "low": "badge-low",
    }.get(level, "badge-low")

    evidence_rows = ""
    for item in validated_evidence:
        source = item.get("source", "")
        finding = item.get("finding", "")
        conf = item.get("confidence", 0)
        evidence_rows += (
            f"<tr><td>{source}</td><td>{finding}</td>"
            f"<td>{conf*100:.1f}%</td></tr>\n"
        )

    breakdown = confidence_result.breakdown or {}
    confidence_rows = ""
    for key, value in breakdown.items():
        confidence_rows += (
            f"<tr><td>{key.replace('_', ' ').title()}</td>"
            f"<td>{value:.2f}</td></tr>\n"
        )

    report_body = (intelligence_report or "Report unavailable.").replace(
        "<", "&lt;"
    ).replace(">", "&gt;")

    return _HTML_TEMPLATE.format(
        aoi_name=aoi_name,
        aoi_id=aoi_id,
        timestamp=now,
        pipeline_version=pipeline_version,
        confidence_score=confidence_result.score,
        change_percentage=fusion_results.get("change_percentage", 0),
        model_agreement=model_agreement,
        badge_class=badge_class,
        report_body=report_body,
        evidence_rows=evidence_rows,
        confidence_rows=confidence_rows,
    )
