class EvidenceValidator:
    """
    Validates evidence generated by different GeoSentinel models
    before it is consumed by the Fusion Engine.

    Current Responsibilities
    ------------------------
    1. Confidence threshold validation
    2. Validation status assignment
    3. Corroboration placeholders
    4. Contradiction placeholders
    """

    def __init__(self):

        self.low_threshold = 0.30
        self.medium_threshold = 0.60

    def validate(self, evidence_items):

        validated_items = []

        for item in evidence_items:

            confidence = float(
                item.get("confidence", 0)
            )

            # -------------------------------------
            # Validation Status
            # -------------------------------------

            if confidence < self.low_threshold:

                status = "rejected"

                reason = (
                    "Confidence below minimum threshold."
                )

            elif confidence < self.medium_threshold:

                status = "uncertain"

                reason = (
                    "Moderate confidence. "
                    "Requires corroboration."
                )

            else:

                status = "validated"

                reason = (
                    "Confidence acceptable."
                )

            # -------------------------------------
            # Validation Metadata
            # -------------------------------------

            item["validation"] = {

                "status": status,

                "reason": reason

            }

            # -------------------------------------
            # Evidence Reasoning Placeholders
            # -------------------------------------

            item["corroborated_by"] = []

            item["contradicted_by"] = []

            item["weight"] = round(
                confidence,
                2
            )

            item["uncertainty"] = round(
                1.0 - confidence,
                2
            )

            validated_items.append(item)

        return validated_items